#:schema node_modules/wrangler/config-schema.json
name = "spicy-wod"
compatibility_date = "2024-12-24"
main = "./server.ts"
assets = { directory = "./build/client" }
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "dev-spicy-db"
database_id = "f866d06d-bc51-47de-ab43-9381a08b5c8a"
migrations_table = "drizzle_migrations"
migrations_dir = "./drizzle"

[[kv_namespaces]]
binding = "USER_SESSIONS"
id = "9ff4a16a8c094b10a4d980b92cd9a1d4"

# # Add production environment configuration
# [env.production]
# name = "spicy-wod"

# # Production database binding
# [[env.production.d1_databases]]
# binding = "DB"
# database_name = "prod-spicy-db"
# database_id = "7b51eef2-3c22-414f-b2cc-d985bec53a14"
# migrations_table = "drizzle_migrations"
# migrations_dir = "./drizzle"

# # Production KV namespace
# [[env.production.kv_namespaces]]
# binding = "USER_SESSIONS"
# id = "385c17a172ad4410ba5e14556aa83bea"
